# Generated by Django 3.1.7 on 2021-04-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='platform_choice_field',
            field=models.CharField(choices=[('1', 'PC'), ('2', 'PS5'), ('3', 'XSX'), ('4', 'Switch'), ('5', 'iOS'), ('6', 'Android'), ('7', 'Arcade'), ('8', 'PS4'), ('9', 'PS3'), ('10', 'Xbox One'), ('11', 'Xbox 360'), ('12', 'Sega'), ('13', 'Wii U'), ('14', 'Wii'), ('15', 'PSP'), ('16', 'Vita'), ('17', '3DS'), ('18', 'RetoPy'), ('19', 'Other Systems')], max_length=50),
        ),
    ]
