# Generated by Django 3.0.8 on 2021-04-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField()),
                ('platform', models.CharField(choices=[('01', 'PC'), ('02', 'PS5'), ('03', 'XSX'), ('04', 'Switch'), ('05', 'iOS'), ('06', 'Android'), ('07', 'Arcade'), ('08', 'PS4'), ('09', 'PS3'), ('10', 'Xbox One'), ('11', 'Xbox 360'), ('12', 'Sega'), ('13', 'Wii U'), ('14', 'Wii'), ('15', 'PSP'), ('16', 'Vita'), ('17', '3DS'), ('18', 'RetoPy'), ('19', 'Other Systems')], max_length=2)),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='cover-art/')),
            ],
        ),
    ]
